# Generated by Django 5.0.1 on 2024-01-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_author_alter_post_author_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_picture_src',
            field=models.ImageField(upload_to='images'),
        ),
    ]
